### ISSUE TITLE
[Bug]: "Something went wrong. Please try again" for bach-ui retrieval time summary & details

### ISSUE THREAD

**Issue by toandn-jpl** [nasa/opera-sds-bach-ui#15]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

https://opera-int-mozart-pop1.jpl.nasa.gov/bach-ui/reporting/retrieval-time/retrieval-time-summary
From bach-ui for retrieval time when I did input: 

Date From: 03/17/2023, 10:00AM
To: 03/21/2023, 11:59:59PM
Presets > Custom

Click > GENERATE
I noticed the following error:

{"message": "cannot generate RetrievalTimeSummaryReport", "details": "'S1B_IW_SLC__1SDV_20200101T014248_20200101T014315_019617_025131_E74A'"}

https://opera-int-mozart-pop1.jpl.nasa.gov/bach-api/reports/RetrievalTimeSummaryReport?startDateTime=2023-03-17T10:00:00Z&endDateTime=2023-03-21T23:59:59Z&reportType=sdp&mime=application%2Fjson

Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
index.jsx?106b:100 Error: Request failed with status code 500
    at createError (createError.js?2d83:16:1)
    at settle (settle.js?467f:17:1)
    at XMLHttpRequest.onloadend (xhr.js?b50d:66:1)
_callee$ @ index.jsx?106b:100
index.jsx?106b:145 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'header')
    at _callee3$ (index.jsx?106b:145:13)
    at tryCatch (runtime.js?96cf:63:16)
    at Generator.invoke [as _invoke] (runtime.js?96cf:294:1)
    at Generator.eval [as next] (runtime.js?96cf:119:1)
    at asyncGeneratorStep (asyncToGenerator.js?ee7c:3:1)
    at _next (asyncToGenerator.js?ee7c:25:1)
    
  No issue with same date/time range with PRODUCTION TIME DETAIL

https://opera-int-mozart-pop1.jpl.nasa.gov/bach-api/reports/ProductionTimeDetailedReport?startDateTime=2023-03-17T10:00Z&endDateTime=2023-03-21T23:59:59Z&reportType=sdp&mime=application%2Fjson

### What did you expect?

I expected to see the generated report for retrieval time summary/ retrieval time details.

### Reproducible steps

```bash
https://opera-int-mozart-pop1.jpl.nasa.gov/bach-ui/reporting/retrieval-time/retrieval-time-summary
From bach-ui for retrieval time when I did input: 

Date From: 03/17/2023, 10:00AM
To: 03/21/2023, 11:59:59PM
Presets > Custom

Click > GENERATE

https://opera-int-mozart-pop1.jpl.nasa.gov/bach-api/reports/RetrievalTimeSummaryReport?startDateTime=2023-03-17T10:00Z&endDateTime=2023-03-21T23:59:59Z&reportType=sdp&mime=application%2Fjson

Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
index.jsx?106b:100 Error: Request failed with status code 500
    at createError (createError.js?2d83:16:1)
    at settle (settle.js?467f:17:1)
    at XMLHttpRequest.onloadend (xhr.js?b50d:66:1)
_callee$ @ index.jsx?106b:100
index.jsx?106b:145 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'header')
    at _callee3$ (index.jsx?106b:145:13)
    at tryCatch (runtime.js?96cf:63:16)
    at Generator.invoke [as _invoke] (runtime.js?96cf:294:1)
    at Generator.eval [as next] (runtime.js?96cf:119:1)
    at asyncGeneratorStep (asyncToGenerator.js?ee7c:3:1)
    at _next (asyncToGenerator.js?ee7c:25:1)
```

### Environment

```bash
https://opera-int-mozart-pop1.jpl.nasa.gov/bach-ui/
Data range date: 

Date From: 03/17/2023, 10:00AM
To: 03/21/2023, 11:59:59PM
```

**Comment by toandn-jpl** [comment]
Running into the same error again with these following ranges:

https://opera-int-mozart-pop1.jpl.nasa.gov/bach-api/reports/RetrievalTimeSummaryReport?startDateTime=2023-03-28T00:00:00Z&endDateTime=2023-03-28T23:59:59Z&reportType=sdp&mime=application%2Fjson

https://opera-int-mozart-pop1.jpl.nasa.gov/bach-api/reports/RetrievalTimeSummaryReport?startDateTime=2023-03-19T00:00Z&endDateTime=2023-03-28T23:59:59Z&reportType=sdp&mime=application%2Fjson

**Comment by hhlee445** [comment]
timeout was set to 60 secs. We had to increase the timeout to 30mins.
