### ISSUE TITLE
[Bug]: Retrieval Time with duplicated entires "Not Available Yet"

### ISSUE THREAD

**Issue by toandn-jpl** [nasa/opera-sds-bach-ui#19]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

When I did submit the following bach-api call from startDateTime=2023-03-27T07:00Z&endDateTime=2023-03-28T19:00 , I noticed duplicated entires with "Not Available Yet"

https://opera-int-mozart-pop1.jpl.nasa.gov/bach-api/reports/RetrievalTimeSummaryReport?startDateTime=2023-03-27T07:00Z&endDateTime=2023-03-28T19:00Z&reportType=sdp&mime=application%2Fjson

![Screenshot 2023-03-29 at 12 18 21 PM](https://user-images.githubusercontent.com/124642133/228645047-a499b98c-177e-44a5-ba85-d58b84eb4808.png)

`[
  {
    "opera_product_short_name": "L3_DSWx_HLS",
    "input_product_short_name": "L2_HLS_L30",
    "retrieval_time_count": 2702,
    "retrieval_time_p90": "01:40:01",
    "retrieval_time_min": "00:18:14",
    "retrieval_time_max": "01:50:05",
    "retrieval_time_median": "01:10:48",
    "retrieval_time_mean": "01:10:41",
    "histogram":...
    },
  {
    "opera_product_short_name": "L3_DSWx_HLS",
    "input_product_short_name": "L2_HLS_S30",
    "retrieval_time_count": 546,
    "retrieval_time_p90": "00:30:31",
    "retrieval_time_min": "00:17:38",
    "retrieval_time_max": "00:34:30",
    "retrieval_time_median": "00:25:39",
    "retrieval_time_mean": "00:25:33",
    "histogram":...
  },
  {
    "opera_product_short_name": "L3_DSWx_HLS",
    "input_product_short_name": "ALL",
    "retrieval_time_count": 3248,
    "retrieval_time_p90": "01:39:23",
    "retrieval_time_min": "00:17:38",
    "retrieval_time_max": "01:50:05",
    "retrieval_time_median": "01:05:16",
    "retrieval_time_mean": "01:03:06",
    "histogram":...
  },
  {
    "opera_product_short_name": "Not Available Yet",
    "input_product_short_name": "L2_HLS_L30",
    "retrieval_time_count": 2702,
    "retrieval_time_p90": "01:40:01",
    "retrieval_time_min": "00:18:14",
    "retrieval_time_max": "01:50:05",
    "retrieval_time_median": "01:10:48",
    "retrieval_time_mean": "01:10:41",
    "histogram":...
  },
{
    "opera_product_short_name": "Not Available Yet",
    "input_product_short_name": "L1_S1_SLC",
    "retrieval_time_count": 119,
    "retrieval_time_p90": "01:17:25",
    "retrieval_time_min": "-2:04:38",
    "retrieval_time_max": "01:28:38",
    "retrieval_time_median": "00:32:23",
    "retrieval_time_mean": "00:24:20",
    "histogram":...
  },
  {
    "opera_product_short_name": "Not Available Yet",
    "input_product_short_name": "ALL",
    "retrieval_time_count": 2821,
    "retrieval_time_p90": "01:39:45",
    "retrieval_time_min": "-2:04:38",
    "retrieval_time_max": "01:50:05",
    "retrieval_time_median": "01:09:52",
    "retrieval_time_mean": "01:08:44",
    "histogram":...
  },
  {
    "opera_product_short_name": "L2_RTC_S1",
    "input_product_short_name": "L1_S1_SLC",
    "retrieval_time_count": 119,
    "retrieval_time_p90": "01:17:25",
    "retrieval_time_min": "-2:04:38",
    "retrieval_time_max": "01:28:38",
    "retrieval_time_median": "00:32:23",
    "retrieval_time_mean": "00:24:20",
    "histogram":...
  },
  {
    "opera_product_short_name": "L2_CSLC_S1",
    "input_product_short_name": "L1_S1_SLC",
    "retrieval_time_count": 119,
    "retrieval_time_p90": "01:17:25",
    "retrieval_time_min": "-2:04:38",
    "retrieval_time_max": "01:28:38",
    "retrieval_time_median": "00:32:23",
    "retrieval_time_mean": "00:24:20",
    "histogram":...
`

### What did you expect?

I expected no duplicated entries with "Not Available Yet" data.

### Reproducible steps

```bash
1. Submit the following 
https://opera-int-mozart-pop1.jpl.nasa.gov/bach-api/reports/RetrievalTimeSummaryReport?startDateTime=2023-03-27T07:00Z&endDateTime=2023-03-28T19:00Z&reportType=sdp&mime=application%2Fjson
2. Check the payload
```

### Environment

```bash
https://opera-int-mozart-pop1.jpl.nasa.gov/bach-ui
https://opera-int-mozart-pop1.jpl.nasa.gov/bach-api
...
```

**Comment by hhlee445** [comment]
@sjlewis-jpl suggested 
1. Remove a column: **OPERA Product Short Name** from the retrieval summary report. 
2. Remove 2 columns: **OPERA Product Short Name** and **OPERA Product Name** from the retrieval detail report.
